### ISSUE TITLE
Issue with module vars being assigned as locals

### ISSUE THREAD

**Issue by orme292** [orme292/admin_scripts#11]
$ ringattack 96.12.166.205 -c London -t mtr

Traceback (most recent call last):
  File "/Users/aorme/github/admin_scripts/ringattack.py", line 337, in <module>
    else: run_predefined_test(args.type, hostname, args.ip)
  File "/Users/aorme/github/admin_scripts/ringattack.py", line 262, in run_predefined_test
    command = "ssh " + script_ssh_options + " " + host + " -- " + command + "; exit 0"
UnboundLocalError: local variable 'command' referenced before assignment

**Comment by orme292** [comment]
resolved with https://github.com/orme292/admin_scripts/commit/ba3d1d7ff3ba33449cd9e48710553862958c02de
