### ISSUE TITLE
-n # specified is greater than available nodes

### ISSUE THREAD

**Issue by orme292** [orme292/admin_scripts#6]
Traceback (most recent call last):
  File "/Users/aorme/github/admin_scripts/ringattack.py", line 303, in <module>
    nodes = find_nodes(url, args.num, country=args.country)
  File "/Users/aorme/github/admin_scripts/ringattack.py", line 228, in find_nodes
    pickNodes = random.sample(range(0, resultCount), numNodes)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 317, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

**Comment by orme292** [comment]
Resolved in 48a65e9
